llm:
  default_provider: "mistral"
  providers:
    mistral:
      api_key: ${MISTRAL_API_KEY}
      model: mistral-large-latest
    openai:
      api_key: ${OPENAI_API_KEY}
      model: gpt-4o-mini
    gemini:
      api_key: ${GEMINI_API_KEY}
      model: gemini-pro
  
database:
  url: sqlite:///chatbot.db

chat:
  max_history: 10
  temperature: 0.7

memory:
  type: sql
  session_ttl: 3600

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"